import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./font.css";
import SideBar from "./components/SideBar";
import RightSidebar from "./components/RightSidebar";
import { AuthProvider } from "../context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Twitter-clone",
  description: "Generated by create next app",
  icons: {
    icon: '/twitter-x.svg'
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <AuthProvider>
          <div className="flex justify-center min-h-screen">
            <SideBar />
            <main className="flex justify-items-start min-w-[600px] border-r  border-r-gray-200">
              {children}
            </main>
            <div className="hidden lg:block">
              <RightSidebar />
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}